# **Question 1**

Create a numpy array starting from 2 till 50 with a stepsize of 3. 


In [2]:
import numpy as np
#creating an array using numpy arange
array1 = np.arange(2, 50, 3)
print(array1)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# **Question 2**

Accept two lists of 5 elements each from the user.  Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [4]:
import numpy as np
list1 = []
list2 = []
for i in range(5):                             #Getting values for list 1 by user
  x=int(input("Values for list1 : "))
  list1.append(x)
for i in range(5):
  x=int(input("Values for list2 : "))          #Getting values for list 2 by user
  list2.append(x)
#converting lists into arrays:
array1 = np.array(list1)
array2 = np.array(list2)
#concatenating both the arrays:
array = np.concatenate((array1, array2))
print("Concatenated array: ", array)
#sorting the array
sortArray = np.sort(array)
print("Sorted array: ", sortArray)

Values for list1 : 50
Values for list1 : 40
Values for list1 : 10
Values for list1 : 20
Values for list1 : 30
Values for list2 : 25
Values for list2 : 20
Values for list2 : 5
Values for list2 : 10
Values for list2 : 15
Concatenated array:  [50 40 10 20 30 25 20  5 10 15]
Sorted array:  [ 5 10 10 15 20 20 25 30 40 50]


# **Question 3**

Write a code snippet to find the dimensions of a ndarray and its size.

In [6]:
import numpy as np
array1 = np.array([[1,2,3],[1,3,5]])                 #2D array
print("Dimensions: ", array1.ndim)       #Printing dimensions of array
print("Size: ", array1.size)             #Printing size of array

Dimensions:  2
Size:  6


# **Question 4**

How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet Hint: np.newaxis, np.expand_dims 

In [8]:
import numpy as np
array1 = np.arange(10)
print("Shape: ",array1.shape)
#converting in row wise
row_array = array1[np.newaxis, :]
print("Shape of 2D Array in row: ",row_array.shape)
#converting in column wise
col_array = array1[:, np.newaxis]
print("Shape of 2D Array in column: ",col_array.shape)

Shape:  (10,)
Shape of 2D Array in row:  (1, 10)
Shape of 2D Array in column:  (10, 1)


# **Question 5**

Consider two square numpy arrays. Stack them vertically and horizontally. Hint: Use vstack(), hstack() 

In [11]:
import numpy as np
#creating two arrays with square values using square function
array1 = np.square([1, 2, 3, 4, 5])
array2 = np.square([11, 12, 13, 14, 15])
#printing the value using stack function
print("Horizontal Stack : ", np.hstack((array1, array2)))
print("Vertical Stack : ", np.vstack((array1, array2)))

Horizontal Stack :  [  1   4   9  16  25 121 144 169 196 225]
Vertical Stack :  [[  1   4   9  16  25]
 [121 144 169 196 225]]


# **Question 6**

How to get unique items and counts of unique items.

In [14]:
import numpy as np
array1 = np.array([1, 4, 9, 16, 25, 121, 144, 169, 196, 225, 1, 2, 3, 4, 5, 11, 12, 13, 14, 15])
#printing unique charater and the count
unique, counts = np.unique(array1, return_counts=True)
array2 = np.asarray((unique, counts)).T
print(array2)


[[  1   2]
 [  2   1]
 [  3   1]
 [  4   2]
 [  5   1]
 [  9   1]
 [ 11   1]
 [ 12   1]
 [ 13   1]
 [ 14   1]
 [ 15   1]
 [ 16   1]
 [ 25   1]
 [121   1]
 [144   1]
 [169   1]
 [196   1]
 [225   1]]
